version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  server:
    build: ./server
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    env_file:
      - ./server/.env

  web:
    build: ./web
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
