version: '3'

networks:
  local:

services:
  mongo-setup-dev:
    container_name: mongo-setup-dev
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: on-failure
    volumes:
      - ./config/mongo/rs-init-dev.sh:/scripts/rs-init-dev.sh
    # entrypoint: ["bash"]
    entrypoint: ["bash", "/scripts/rs-init-dev.sh" ]
    networks:
      - local
    depends_on:
      - mongodb0
      - mongodb1
      - mongodb2

  mongodb0:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb0
    cpus: 0.5
    ports:
      - 27017:27017
    volumes:
      - ./config/data/dev0:/data/db
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodb0

  mongodb1:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb1
    cpus: 0.5
    ports:
      - 27018:27017
    volumes:
     - ./config/data/dev1:/data/db
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodb1

  mongodb2:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb2
    cpus: 0.5
    ports:
      - 27019:27017
    volumes:
      - ./config/data/dev2:/data/db
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodb2

  mongo-setup-test:
    container_name: mongo-setup-test
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: on-failure
    volumes:
      - ./config/mongo/rs-init-test.sh:/scripts/rs-init-test.sh
    # entrypoint: ["bash"]
    entrypoint: ["bash", "/scripts/rs-init-test.sh" ]
    networks:
      - local
    depends_on:
      - mongodbtest0
      - mongodbtest1
      - mongodbtest2

  mongodbtest0:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodbtest0
    cpus: 0.5
    ports:
      - 27020:27017
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodbtest0

  mongodbtest1:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodbtest1
    cpus: 0.5
    ports:
      - 27021:27017
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodbtest1

  mongodbtest2:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodbtest2
    cpus: 0.5
    ports:
      - 27022:27017
    networks:
      - local
    command: mongod --replSet rs0 --bind_ip localhost,mongodbtest2

  server:
    build: ./server
    restart: always
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    networks:
      - local

  web:
    build: ./web
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./web:/app
    networks:
      - local
